import "@radix-ui/themes/styles.css";
import "@/app/theme-config.css"
import "./globals.css";
import type {Metadata} from "next";
import {Geist, Geist_Mono, Inter} from "next/font/google";

import NavBar from "@/app/NavBar";
import {Theme} from "@radix-ui/themes";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter"
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`$ ${inter.variable} antialiased`}>
        <Theme appearance='light' accentColor="violet">

            <NavBar/>
            <main className='p-5'>{children}</main>

        </Theme>
        </body>
        </html>
    );
}
